Resolve Rust warnings and Clippy lints
Summary:
```lang=text
warning: this `map_or` can be simplified
   --> fbcode/target_determinator/btd/src/check.rs:159:20
    |
159 |                   && base_targets_map
    |  ____________________^
160 | |                     .get(&target.label_key())
161 | |                     .map_or(true, |t| !t.deps.iter().any(|d| d == dep))
    | |_______________________________________________________________________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
    = note: `#[warn(clippy::unnecessary_map_or)]` on by default
help: use is_none_or instead
    |
161 -                     .map_or(true, |t| !t.deps.iter().any(|d| d == dep))
161 +                     .is_none_or(|t| !t.deps.iter().any(|d| d == dep))
    |

warning: this `map_or` can be simplified
   --> fbcode/target_determinator/citrace/src/orchestrator/orchestrator.rs:539:21
    |
539 | /                     job.args
540 | |                         .get("build_properties")
541 | |                         .and_then(|v| v.get("buck_target"))
542 | |                         .and_then(|v| v.as_str())
543 | |                         .map_or(false, |v| target.matches_str(&format!("fbsource{}", v)))
    | |_________________________________________________________________________________________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
    = note: `#[warn(clippy::unnecessary_map_or)]` on by default
help: use is_some_and instead
    |
543 -                         .map_or(false, |v| target.matches_str(&format!("fbsource{}", v)))
543 +                         .is_some_and(|v| target.matches_str(&format!("fbsource{}", v)))
    |

warning: spawned process is never `wait()`ed on
  --> fbcode/target_determinator/citrace/src/types/verse.rs:62:19
   |
62 |           let cat = Command::new("cat")
   |  ___________________^
63 | |             .arg(targets_file.path())
64 | |             .stdout(Stdio::piped())
65 | |             .spawn()
66 | |             .unwrap();
   | |_____________________^
   |
   = help: consider calling `.wait()`
   = note: not doing so might leave behind zombie processes
   = note: see https://doc.rust-lang.org/stable/std/process/struct.Child.html#warning
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#zombie_processes
   = note: `#[warn(clippy::zombie_processes)]` on by default

Target `fbcode//target_determinator/configerator_td:configerator_td_bin-unittest` has unused dependencies:
    fbcode//configerator/configo/if:configo-rust-srclients: configo_thrift_srclients

Target `fbcode//target_determinator/configerator_td:lib` has unused dependencies:
    fbsource//third-party/rust:futures: futures

warning: unused variable: `succeeded_resolving_hash`
  --> fbcode/target_determinator/configerator_td/src/lib.rs:30:28
   |
30 |     let (created_session, (succeeded_resolving_hash, resolved_hash)) = tokio::try_join!(
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_succeeded_resolving_hash`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: variable does not need to be mutable
  --> fbcode/target_determinator/configerator_td/src/lib.rs:22:5
   |
22 |     mut configerator_canary_args: HashMap<JobArgToAdd, serde_json::Value>,
   |     ----^^^^^^^^^^^^^^^^^^^^^^^^
   |     |
   |     help: remove this `mut`
   |
   = note: `#[warn(unused_mut)]` on by default

Target `fbcode//target_determinator/configerator_td:lib-unittest` has unused dependencies:
    fbsource//third-party/rust:futures: futures

Target `fbcode//target_determinator/sandcastle_dependency_service_v2/service:service_handler` has unused dependencies:
    fbsource//third-party/rust:serde: serde

Target `fbcode//target_determinator/sandcastle_dependency_service_v2/service:service_handler-unittest` has unused dependencies:
    fbsource//third-party/rust:serde: serde

warning: this `map_or` can be simplified
   --> fbcode/target_determinator/scheduler/src/runway_sandcastle_job.rs:152:20
    |
152 |                 if jest_e2e_app_name.as_ref().map_or(false, |n| !n.is_empty()) {
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
    = note: `#[warn(clippy::unnecessary_map_or)]` on by default
help: use is_some_and instead
    |
152 -                 if jest_e2e_app_name.as_ref().map_or(false, |n| !n.is_empty()) {
152 +                 if jest_e2e_app_name.as_ref().is_some_and(|n| !n.is_empty()) {
    |

warning: this `.filter_map` can be written more simply
    --> fbcode/target_determinator/scheduler/src/lib.rs:995:62
     |
995  |           let failed_to_schedule_group_ids: HashSet<&String> = dep_map
     |  ______________________________________________________________^
996  | |             .dependency_group_id_to_aliases
997  | |             .keys()
998  | |             .filter_map(|id| {
...    |
1012 | |             })
     | |______________^ help: try instead: `filter`
     |
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_filter_map
     = note: `#[warn(clippy::unnecessary_filter_map)]` on by default

warning: this `map_or` can be simplified
    --> fbcode/target_determinator/scheduler/src/lib.rs:999:20
     |
999  |                   if dep_map
     |  ____________________^
1000 | |                     .dependency_group_id_to_aliases
1001 | |                     .get(id)
1002 | |                     .map_or(false, |aliases| {
...    |
1005 | |                             .any(|a| failed_to_schedule_aliases.contains(a))
1006 | |                     })
     | |______________________^
     |
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
help: use is_some_and instead
     |
1002 -                     .map_or(false, |aliases| {
1002 +                     .is_some_and(|aliases| {
     |

warning: this `.filter_map` can be written more simply
    --> fbcode/target_determinator/scheduler/src/lib.rs:1015:66
     |
1015 |           let successfully_scheduled_group_ids: HashSet<&String> = dep_map
     |  __________________________________________________________________^
1016 | |             .dependency_group_id_to_aliases
1017 | |             .keys()
1018 | |             .filter_map(|id| {
...    |
1032 | |             })
     | |______________^ help: try instead: `filter`
     |
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_filter_map

warning: this `map_or` can be simplified
    --> fbcode/target_determinator/scheduler/src/lib.rs:1019:20
     |
1019 |                   if dep_map
     |  ____________________^
1020 | |                     .dependency_group_id_to_aliases
1021 | |                     .get(id)
1022 | |                     .map_or(false, |aliases| {
...    |
1025 | |                             .all(|a| scheduled_alias_to_job.contains_key(a))
1026 | |                     })
     | |______________________^
     |
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
help: use is_some_and instead
     |
1022 -                     .map_or(false, |aliases| {
1022 +                     .is_some_and(|aliases| {
     |

Target `fbcode//target_determinator/scheduler:lib-unittest` has unused dependencies:
    fbcode//sandcastle/job_spec_override:sandcastle_qe2_client: sandcastle_qe2_client

Target `fbcode//target_determinator/td_util:lib` has unused dependencies:
    fbsource//third-party/rust:_ctor-0.1.16: ctor

Target `fbcode//target_determinator/td_util:lib-unittest` has unused dependencies:
    fbsource//third-party/rust:_ctor-0.1.16: ctor

warning: this `map_or` can be simplified
  --> fbcode/target_determinator/verifiable/src/directives.rs:35:5
   |
35 | /     app_specific_build_directives.map_or(false, |app_specific_build_directives| {
36 | |         app_specific_build_directives.iter().any(|directive| {
37 | |             if exactly && project != TdProject::Fbobjc {
38 | |                 name == directive
...  |
42 | |         })
43 | |     })
   | |______^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
   = note: `#[warn(clippy::unnecessary_map_or)]` on by default
help: use is_some_and instead
   |
35 -     app_specific_build_directives.map_or(false, |app_specific_build_directives| {
35 +     app_specific_build_directives.is_some_and(|app_specific_build_directives| {
   |

warning: this `map_or` can be simplified
   --> fbcode/target_determinator/verifiable/src/verifiable.rs:573:9
    |
573 | /         self.metadata
574 | |             .get("stable_tags")
575 | |             .and_then(|tags| tags.as_str())
576 | |             .map_or(false, |tag| !tag.is_empty())
    | |_________________________________________________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
help: use is_some_and instead
    |
576 -             .map_or(false, |tag| !tag.is_empty())
576 +             .is_some_and(|tag| !tag.is_empty())
    |

warning: this `map_or` can be simplified
   --> fbcode/target_determinator/verifiable/src/verifiable.rs:586:9
    |
586 | /         self.get_rule_type_metadata()
587 | |             .map_or(false, |rule_type| rule_type.starts_with("python_"))
    | |________________________________________________________________________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
help: use is_some_and instead
    |
587 -             .map_or(false, |rule_type| rule_type.starts_with("python_"))
587 +             .is_some_and(|rule_type| rule_type.starts_with("python_"))
    |

warning: this `map_or` can be simplified
   --> fbcode/target_determinator/verifiable/src/verifiable.rs:768:9
    |
768 | /         self.metadata
769 | |             .get(&VerifiableMetadataKey::SupportsGpu.to_string())
770 | |             .map_or(false, |v| v.as_str() == Some("true"))
    | |__________________________________________________________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
help: use is_some_and instead
    |
770 -             .map_or(false, |v| v.as_str() == Some("true"))
770 +             .is_some_and(|v| v.as_str() == Some("true"))
    |

warning: this `map_or` can be simplified
   --> fbcode/target_determinator/verifiable/src/verifiable.rs:774:9
    |
774 | /         self.metadata
775 | |             .get(&VerifiableMetadataKey::RequiresMac.to_string())
776 | |             .map_or(false, |v| v.as_str() == Some("true"))
    | |__________________________________________________________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
help: use is_some_and instead
    |
776 -             .map_or(false, |v| v.as_str() == Some("true"))
776 +             .is_some_and(|v| v.as_str() == Some("true"))
    |

warning: this `map_or` can be simplified
   --> fbcode/target_determinator/verifiable/src/verifiable.rs:792:9
    |
792 | /         self.metadata
793 | |             .get(&VerifiableMetadataKey::TestFramework.to_string())
794 | |             .map_or(false, |v| v.as_str() == Some("test-framework=40:cogwheel"))
    | |________________________________________________________________________________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
help: use is_some_and instead
    |
794 -             .map_or(false, |v| v.as_str() == Some("test-framework=40:cogwheel"))
794 +             .is_some_and(|v| v.as_str() == Some("test-framework=40:cogwheel"))
    |

warning: this `map_or` can be simplified
   --> fbcode/target_determinator/verifiable_matcher/src/rl_verifiable_node_builder.rs:762:5
    |
762 | /     workflow
763 | |         .labels
764 | |         .iter()
765 | |         .find(|&label| label.starts_with("translator_run_types:"))
766 | |         .map_or(false, |label| {
767 | |             parse_run_types(label).contains(&run_type.to_string())
768 | |         })
    | |__________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
    = note: `#[warn(clippy::unnecessary_map_or)]` on by default
help: use is_some_and instead
    |
766 -         .map_or(false, |label| {
766 +         .is_some_and(|label| {
    |

warning: doc list item overindented
  --> fbcode/target_determinator/verifiable_matcher/src/xplat_verifiable_node_builder.rs:42:9
   |
42 |     ///     a) Include if target is labeled with expected platform label
   |         ^^^^ help: try using `   ` (3 spaces)
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_overindented_list_items
   = note: `#[warn(clippy::doc_overindented_list_items)]` on by default

warning: doc list item overindented
  --> fbcode/target_determinator/verifiable_matcher/src/xplat_verifiable_node_builder.rs:43:9
   |
43 |     ///     b) Or if target matches expected target rule types.
   |         ^^^^ help: try using `   ` (3 spaces)
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_overindented_list_items

warning: this `map_or` can be simplified
   --> fbcode/target_determinator/verifiable_matcher/src/xplat_verifiable_node_builder.rs:99:12
    |
99  |           if self
    |  ____________^
100 | |             .matcher
101 | |             .map_or(false, |matcher| matcher.matches(target))
    | |_____________________________________________________________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
help: use is_some_and instead
    |
101 -             .map_or(false, |matcher| matcher.matches(target))
101 +             .is_some_and(|matcher| matcher.matches(target))
    |

error[E0061]: this function takes 5 arguments but 4 arguments were supplied
   --> fbcode/target_determinator/verifiable_matcher/src/runway_verifiable_node_builder.rs:452:22
    |
452 |         let result = build_verifiable_nodes(
    |                      ^^^^^^^^^^^^^^^^^^^^^^
...
465 |             None,
    |             ---- argument #3 of type `&[&btd::Btd]` is missing
    |
note: function defined here
   --> fbcode/target_determinator/verifiable_matcher/src/runway_verifiable_node_builder.rs:179:8
    |
179 | pub fn build_verifiable_nodes(
    |        ^^^^^^^^^^^^^^^^^^^^^^
...
182 |     other_targets: &[&Btd],
    |     ----------------------
help: provide the argument
    |
452 ~         let result = build_verifiable_nodes(ScheduleType::Continuous, &[&Btd {
453 +                 target: "test".to_string(),
454 +                 rule_type: "runway_test".to_string(),
455 +                 depth: 0,
456 +                 labels: vec![
457 +                     "runway_tpx_timeout_s=60".to_string(),
458 +                     "ci:continuous:linux:dev:root".to_string(),
459 +                 ],
460 +                 oncall: None,
461 +                 reason: Btd::sample_impact("test"),
462 ~             }], /* &[&btd::Btd] */, None, None);
    |

warning: called `Iterator::last` on a `DoubleEndedIterator`; this will needlessly iterate the entire iterator
   --> fbcode/target_determinator/verse/adaptors/citadel/multistage_verse.rs:111:10
    |
111 |         .last()
    |          ^^^^^^ help: try: `next_back()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#double_ended_iterator_last
    = note: `#[warn(clippy::double_ended_iterator_last)]` on by default

warning: spawned process is never `wait()`ed on
   --> fbcode/target_determinator/verse/cli_lib/src/interactive_evaluate.rs:290:31
    |
290 |                       let cat = ShellCommand::new("cat")
    |  _______________________________^
291 | |                         .arg(dot_file.as_os_str())
292 | |                         .stdout(Stdio::piped())
293 | |                         .spawn()
294 | |                         .unwrap();
    | |_________________________________^
    |
    = help: consider calling `.wait()`
    = note: not doing so might leave behind zombie processes
    = note: see https://doc.rust-lang.org/stable/std/process/struct.Child.html#warning
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#zombie_processes
    = note: `#[warn(clippy::zombie_processes)]` on by default

errors: 1; warnings: 30
```

Reviewed By: aniketmathur

Differential Revision: D72693013

fbshipit-source-id: 1bd4cb55e31e173c7454b954d4c15993ca798461